-- ============================================================
-- Xtracting archive - schema
-- PostgreSQL 18 + TimescaleDB
--
-- One database for extraction results, in every language you asked for.
--
-- THREE COLUMNS ARE ON EVERY TABLE, and they are what makes this worth sharing
-- as a schema rather than keeping private:
--
--   text_project    which project the row belongs to. An API key is bound to
--                   one project, so several can share an archive and still be
--                   pulled apart later without ambiguity.
--   text_language   which language version this row is. The English original is
--                   stored as 'English'; every requested translation is stored
--                   as its own complete set of rows with the same task id.
--   text_task_id    which task produced it. This is what a collector reads to
--                   decide what it has already archived, and what you delete by
--                   if you ever need to remove one task's output.
--
-- All three are plain B-tree indexes on every table, deliberately NOT hypertable
-- dimensions. Partitioning by them would make chunks that never fill, and the
-- queries they serve are equality filters, which a B-tree answers better than a
-- partition ever will.
--
-- SEPARABILITY. Because every row carries its project, and because nothing is
-- ever shared between projects, an archive that outgrows one database can be
-- split by copying rows WHERE text_project = '...'. Nothing has to be untangled
-- first. That is also why the same vocabulary entry is stored once per project
-- rather than once globally - see the uniqueness rule below.
--
-- There is no table for raw task text. This database is for results. The
-- submitted content stays with you and is deleted on the platform after an
-- hour; keeping a second copy here would quietly undo that.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

CREATE SCHEMA IF NOT EXISTS processed_data;


CREATE SCHEMA IF NOT EXISTS monitoring;

-- ============================================================
-- Vocabularies
--
-- Plain tables, NOT hypertables, and that is deliberate. A vocabulary grows
-- with the number of distinct names, which saturates - it is not a time series,
-- and partitioning it by day would produce chunks of four rows.
--
-- More importantly it lets the uniqueness rule be enforced by the database:
--
--     UNIQUE (text_name, text_project, text_language)
--
-- A hypertable cannot have a unique index that omits its partitioning column,
-- so here the constraint would have to include date_added - and then an insert
-- a second later is a different row and ON CONFLICT never fires. The result is
-- a vocabulary that gains one duplicate per task, forever.
--
-- The same type name in two projects is stored TWICE, once per project. That is
-- the point: 'Machine' in project A and 'Machine' in project B are not one
-- entry with two owners, and an archive that merged them could not be split
-- apart again.
-- ============================================================

DO $$
DECLARE
    type_tables TEXT[] := ARRAY[
        'source_types', 'entity_types', 'event_types', 'location_types',
        'perspective_types', 'rating_types', 'connection_types', 'relation_types',
        'attribute_types', 'unit_types', 'importance_types',
        'market_topic_types', 'outlook_types', 'sentiment_types',
        'rating_values', 'trustlist_types'
    ];
    t TEXT;
BEGIN
    FOREACH t IN ARRAY type_tables LOOP
        EXECUTE format($f$
            CREATE TABLE processed_data.%I (
                bigint_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                date_added       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                text_name        TEXT NOT NULL,
                text_project     TEXT NOT NULL DEFAULT '',
                text_language    TEXT NOT NULL DEFAULT 'English',
                text_task_id     TEXT NOT NULL DEFAULT '',
                text_job_id      TEXT NOT NULL DEFAULT '',
                text_description TEXT NOT NULL DEFAULT '',
                float_value      DOUBLE PRECISION,
                bool_enabled     BOOLEAN NOT NULL DEFAULT true,
                UNIQUE (text_name, text_project, text_language)
            )
        $f$, t);

        EXECUTE format($f$CREATE INDEX idx_%s_project  ON processed_data.%I (text_project)$f$, t, t);
        EXECUTE format($f$CREATE INDEX idx_%s_language ON processed_data.%I (text_language)$f$, t, t);
        EXECUTE format($f$CREATE INDEX idx_%s_task     ON processed_data.%I (text_task_id)$f$, t, t);
    END LOOP;
END
$$;

ALTER TABLE processed_data.connection_types ADD COLUMN bool_reversed BOOLEAN NOT NULL DEFAULT false;

-- ============================================================
-- Data tables
--
-- Hypertables on date_added, one-day chunks, compressed a day after each chunk
-- closes.
--
-- Keyed by identity, never by name. A structured extraction can legitimately
-- repeat a name: a location called "EU" belonging to two entities of one task,
-- an attribute called "Retention Period" on two entities. Those are two records,
-- not one written twice. Keying on the name made the second one a duplicate and
-- aborted the whole job's transaction, which cost four jobs before it was
-- found. date_added leads the key because TimescaleDB requires the
-- partitioning column in every unique index. Recycling by name is the *_types
-- tables' job, and they keep their UNIQUE (text_name, text_project, text_language).
--
-- text_fk_* columns carry no formal foreign keys: a hypertable cannot be the
-- target of one. The collector resolves references before it writes.
-- ============================================================

CREATE TABLE processed_data.sources (
    date_added              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name               TEXT NOT NULL,
    text_project            TEXT NOT NULL DEFAULT '',
    text_language           TEXT NOT NULL DEFAULT 'English',
    text_task_id            TEXT NOT NULL DEFAULT '',
    bigint_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id             TEXT,
    text_source_id          TEXT,
    text_uri                TEXT NOT NULL DEFAULT '',
    -- sha256 of exactly what was submitted, hex. Compare it against a file on
    -- disk and you know whether that file has already been extracted in this
    -- state - without re-uploading it, and without trusting a filename or a
    -- modification date. A whole directory becomes a set of hashes to diff
    -- against this column.
    text_content_hash       TEXT NOT NULL DEFAULT '',
    text_type               TEXT NOT NULL DEFAULT '',
    text_importance         TEXT NOT NULL DEFAULT '',
    text_summary            TEXT NOT NULL DEFAULT '',
    text_reason             TEXT NOT NULL DEFAULT '',
    text_keywords           TEXT NOT NULL DEFAULT '',
    text_evidences          TEXT,
    bool_trustful           BOOLEAN NOT NULL DEFAULT false,
    -- Both nullable: a document that does not state when it was written has no
    -- creation date, and the extraction returns null rather than a guess. There
    -- is deliberately no date_fetched - the model cannot know when a document
    -- was retrieved, and asked for it anyway it invented one.
    date_written            TIMESTAMPTZ,
    date_edited             TIMESTAMPTZ,
    -- When the task was commissioned and when its evaluation finished. Both
    -- come from the API; without them a row cannot be placed on a timeline
    -- other than by when this collector happened to fetch it.
    date_commissioned       TIMESTAMPTZ,
    date_evaluated          TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

CREATE TABLE processed_data.entities (
    date_added              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name               TEXT NOT NULL,
    text_project            TEXT NOT NULL DEFAULT '',
    text_language           TEXT NOT NULL DEFAULT 'English',
    text_task_id            TEXT NOT NULL DEFAULT '',
    bigint_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id             TEXT,
    text_entity_id          TEXT,
    text_fk_source_id       TEXT,
    text_type               TEXT NOT NULL DEFAULT '',
    text_description        TEXT,
    text_keywords           TEXT,
    text_relation_to_source TEXT NOT NULL DEFAULT '',
    text_evidences          TEXT,
    date_commissioned       TIMESTAMPTZ,
    date_evaluated          TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

CREATE TABLE processed_data.locations (
    date_added              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name               TEXT NOT NULL,
    text_project            TEXT NOT NULL DEFAULT '',
    text_language           TEXT NOT NULL DEFAULT 'English',
    text_task_id            TEXT NOT NULL DEFAULT '',
    bigint_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id             TEXT,
    text_fk_entity_id       TEXT,
    text_fk_source_id       TEXT,
    text_type               TEXT NOT NULL DEFAULT '',
    text_description        TEXT NOT NULL DEFAULT '',
    text_address            TEXT,
    text_relation_to_source TEXT NOT NULL DEFAULT '',
    text_evidences          TEXT,
    float_latitude          DOUBLE PRECISION,
    float_longitude         DOUBLE PRECISION,
    date_commissioned       TIMESTAMPTZ,
    date_evaluated          TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

CREATE TABLE processed_data.events (
    date_added              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name               TEXT NOT NULL,
    text_project            TEXT NOT NULL DEFAULT '',
    text_language           TEXT NOT NULL DEFAULT 'English',
    text_task_id            TEXT NOT NULL DEFAULT '',
    bigint_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id             TEXT,
    text_fk_source_id       TEXT,
    text_type               TEXT NOT NULL DEFAULT '',
    text_description        TEXT NOT NULL DEFAULT '',
    text_reason             TEXT,
    text_relation_to_source TEXT NOT NULL DEFAULT '',
    text_evidences          TEXT,
    date_eventdate          TIMESTAMPTZ,
    date_commissioned       TIMESTAMPTZ,
    date_evaluated          TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

CREATE TABLE processed_data.ratings (
    date_added              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name               TEXT NOT NULL,
    text_project            TEXT NOT NULL DEFAULT '',
    text_language           TEXT NOT NULL DEFAULT 'English',
    text_task_id            TEXT NOT NULL DEFAULT '',
    bigint_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id             TEXT,
    text_fk_entity_id       TEXT,
    text_fk_source_id       TEXT,
    text_rating_name        TEXT NOT NULL DEFAULT '',
    text_perspective        TEXT NOT NULL DEFAULT '',
    -- Egregious | Very Bad | Bad | Neutral | Good | Very Good | Excellent
    text_rating_value       TEXT NOT NULL DEFAULT '',
    text_reason             TEXT NOT NULL DEFAULT '',
    text_relation_to_source TEXT NOT NULL DEFAULT '',
    text_evidences          TEXT,
    date_commissioned       TIMESTAMPTZ,
    date_evaluated          TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

CREATE TABLE processed_data.connections (
    date_added                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name                 TEXT NOT NULL,
    text_project              TEXT NOT NULL DEFAULT '',
    text_language             TEXT NOT NULL DEFAULT 'English',
    text_task_id              TEXT NOT NULL DEFAULT '',
    bigint_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id               TEXT,
    text_fk_source_id         TEXT,
    text_fk_parent_entity_id  TEXT,
    text_fk_child_entity_id   TEXT,
    text_type_parent_to_child TEXT NOT NULL DEFAULT '',
    text_type_child_to_parent TEXT NOT NULL DEFAULT '',
    text_reason               TEXT NOT NULL DEFAULT '',
    text_relation_to_source   TEXT NOT NULL DEFAULT '',
    text_evidences            TEXT,
    date_commissioned         TIMESTAMPTZ,
    date_evaluated            TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

-- One row per (event, entity) pair.
--
-- An event belongs to its document and may also name what it is about, in an
-- Events[].entityids list. A list needs rows, not a column: "which events touched
-- this plant" has to be answerable from the entity side too, and an array would
-- make that a scan while every other relationship here is a join.
--
-- Modelled on connections, which is the other table whose whole job is to hold a
-- reference. The event is carried by its bigint_id because an event has no id of
-- its own in the extraction - unlike an entity, which brings "ent:...".
--
-- An event with no entityids writes no rows at all. That is the ordinary case
-- and not a gap: it means the event is about the document rather than anything
-- in it.
CREATE TABLE processed_data.event_entities (
    date_added              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name               TEXT NOT NULL,
    text_project            TEXT NOT NULL DEFAULT '',
    text_language           TEXT NOT NULL DEFAULT 'English',
    text_task_id            TEXT NOT NULL DEFAULT '',
    bigint_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id             TEXT,
    text_fk_source_id       TEXT,
    bigint_fk_event_id      BIGINT,
    text_fk_entity_id       TEXT,
    date_commissioned       TIMESTAMPTZ,
    date_evaluated          TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

CREATE TABLE processed_data.attributes (
    date_added              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name               TEXT NOT NULL,
    text_project            TEXT NOT NULL DEFAULT '',
    text_language           TEXT NOT NULL DEFAULT 'English',
    text_task_id            TEXT NOT NULL DEFAULT '',
    bigint_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id             TEXT,
    text_fk_entity_id       TEXT,
    text_fk_source_id       TEXT,
    text_type               TEXT NOT NULL DEFAULT '',
    text_unit               TEXT NOT NULL DEFAULT '',
    text_value              TEXT NOT NULL DEFAULT '',
    -- The numeric reading of text_value where there is one. Kept beside the
    -- original rather than instead of it: "approx. 12.5" is a real answer and
    -- must not be lost to make a column tidy.
    float_value             DOUBLE PRECISION,
    text_description        TEXT,
    text_reason             TEXT,
    text_relation_to_source TEXT NOT NULL DEFAULT '',
    text_evidences          TEXT,
    date_commissioned       TIMESTAMPTZ,
    date_evaluated          TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

-- Market insights. The vocabulary here is the one the API returns: an outlook
-- points a direction and a sentiment says how strongly a source read. Neither
-- expresses an instruction, and nothing in this table should be treated as one.
CREATE TABLE processed_data.market_insights (
    date_added                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name                 TEXT NOT NULL,
    text_project              TEXT NOT NULL DEFAULT '',
    text_language             TEXT NOT NULL DEFAULT 'English',
    text_task_id              TEXT NOT NULL DEFAULT '',
    bigint_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id               TEXT,
    text_fk_entity_id         TEXT,
    text_fk_source_id         TEXT,
    text_topic                TEXT NOT NULL DEFAULT '',
    -- Rising | Declining | Neutral | Unset
    text_long_term_outlook    TEXT NOT NULL DEFAULT 'Unset',
    text_short_term_outlook   TEXT NOT NULL DEFAULT 'Unset',
    -- Very Negative | Negative | Slightly Negative | Neutral
    --              | Slightly Positive | Positive | Very Positive | Unset
    text_long_term_sentiment  TEXT NOT NULL DEFAULT 'Unset',
    text_short_term_sentiment TEXT NOT NULL DEFAULT 'Unset',
    bool_high_relevance       BOOLEAN NOT NULL DEFAULT false,
    text_reason               TEXT,
    text_relation_to_source   TEXT NOT NULL DEFAULT '',
    text_evidences            TEXT,
    date_commissioned         TIMESTAMPTZ,
    date_evaluated            TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

CREATE TABLE processed_data.source_importances_by_perspective (
    date_added        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name         TEXT NOT NULL,
    text_project      TEXT NOT NULL DEFAULT '',
    text_language     TEXT NOT NULL DEFAULT 'English',
    text_task_id      TEXT NOT NULL DEFAULT '',
    bigint_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id       TEXT,
    text_fk_source_id TEXT,
    text_perspective  TEXT NOT NULL DEFAULT '',
    -- Not Important | Low Importance | Medium Importance
    --               | High Importance | Critical Importance
    text_importance   TEXT NOT NULL DEFAULT '',
    text_reason       TEXT,
    date_commissioned TIMESTAMPTZ,
    date_evaluated    TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

-- One row per task and language. This is the table a collector reads to decide
-- what it already has: every completed task writes exactly one row here, in the
-- same transaction as its data, even when the extraction produced nothing at
-- all. A data table can legitimately be empty for a task; this one cannot.
CREATE TABLE processed_data.tasks (
    date_added           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name            TEXT NOT NULL,
    text_project         TEXT NOT NULL DEFAULT '',
    text_language        TEXT NOT NULL DEFAULT 'English',
    text_task_id         TEXT NOT NULL DEFAULT '',
    bigint_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text_job_id          TEXT NOT NULL DEFAULT '',
    integer_task_index   INTEGER NOT NULL DEFAULT 0,
    text_status          TEXT NOT NULL DEFAULT '',
    text_source_uri      TEXT NOT NULL DEFAULT '',
    -- Also here, so "has this file been extracted?" can be answered without
    -- touching a data table that may legitimately be empty.
    text_content_hash    TEXT NOT NULL DEFAULT '',
    text_tag             TEXT,
    text_error           TEXT,
    float_cost_chf       DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    bigint_processing_ms BIGINT,
    date_commissioned    TIMESTAMPTZ,
    date_evaluated       TIMESTAMPTZ,
    PRIMARY KEY (date_added, bigint_id)
);

DO $$
DECLARE
    data_tables TEXT[] := ARRAY[
        'sources', 'entities', 'locations', 'events', 'ratings', 'connections',
        'attributes', 'market_insights', 'source_importances_by_perspective',
        'event_entities', 'tasks'
    ];
    t TEXT;
    seg TEXT;
BEGIN
    FOREACH t IN ARRAY data_tables LOOP
        EXECUTE format(
            $f$SELECT create_hypertable('processed_data.%I', 'date_added',
                                        chunk_time_interval => INTERVAL '1 day')$f$, t);

        -- Segment by what analyses actually filter on. text_name is the
        -- selective one: a given name sits in a few segments, so a name lookup
        -- skips the rest without decompressing them. text_project and
        -- text_language are not selective - every chunk holds every project and
        -- every language - but naming them here stores each value once per
        -- segment instead of compressing it as a column, which makes the chunk
        -- smaller rather than larger. See the header for the measurements.
        SELECT CASE WHEN EXISTS (
                   SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'processed_data'
                     AND table_name = t AND column_name = 'text_type')
               THEN 'text_name, text_type, text_project, text_language'
               ELSE 'text_name, text_project, text_language'
               END
          INTO seg;

        EXECUTE format($f$
            ALTER TABLE processed_data.%I SET (
                timescaledb.compress,
                timescaledb.compress_segmentby = %L,
                timescaledb.compress_orderby = 'date_added DESC'
            )
        $f$, t, seg);
        -- THIRTY DAYS, NOT ONE.
        --
        -- A day meant that all but the newest chunk was compressed, and the
        -- dashboard reads the whole archive rather than its newest day: every
        -- filtered scan then pays to decompress what it walks over. Measured
        -- on a real archive, one place search planned over 550 chunks and
        -- spent eight seconds in them.
        --
        -- Thirty days keeps the working set - what anybody is looking at
        -- while it is being collected and checked - readable at full speed,
        -- and still compresses everything behind it, which is where the
        -- volume is. The number is the customer's: a month is how far back a
        -- question about "recent" reaches here.
        -- The policy lives in init/05-policies.sql, which owns every retention and
        -- compression number in one place and, unlike this file, may be applied to an
        -- archive that already exists.

        -- The three identity columns, each on its own. Plain B-tree, not
        -- partitioning dimensions - see the header.
        EXECUTE format($f$CREATE INDEX idx_%s_project  ON processed_data.%I (text_project)$f$, t, t);
        EXECUTE format($f$CREATE INDEX idx_%s_language ON processed_data.%I (text_language)$f$, t, t);
        EXECUTE format($f$CREATE INDEX idx_%s_task     ON processed_data.%I (text_task_id)$f$, t, t);
        -- And the combination a collector actually asks for: which tasks of
        -- this project are already here. Time-ordered, because it only ever
        -- looks at a short recent window.
        EXECUTE format(
            $f$CREATE INDEX idx_%s_project_task ON processed_data.%I
                 (text_project, text_task_id, date_added DESC)$f$, t, t);
    END LOOP;
END
$$;

-- The joins a dashboard makes.
-- The lookup that answers "have I already extracted this exact file?".
CREATE INDEX idx_sources_content_hash ON processed_data.sources (text_content_hash);
CREATE INDEX idx_tasks_content_hash   ON processed_data.tasks (text_content_hash);
CREATE INDEX idx_sources_source_id  ON processed_data.sources (text_source_id);
CREATE INDEX idx_entities_entity_id ON processed_data.entities (text_entity_id);
CREATE INDEX idx_attributes_entity  ON processed_data.attributes (text_fk_entity_id);
CREATE INDEX idx_ratings_entity     ON processed_data.ratings (text_fk_entity_id);
CREATE INDEX idx_connections_parent ON processed_data.connections (text_fk_parent_entity_id);
CREATE INDEX idx_connections_child  ON processed_data.connections (text_fk_child_entity_id);
CREATE INDEX idx_event_entities_event  ON processed_data.event_entities (bigint_fk_event_id);
CREATE INDEX idx_event_entities_entity ON processed_data.event_entities (text_fk_entity_id);
CREATE INDEX idx_market_entity      ON processed_data.market_insights (text_fk_entity_id);
CREATE INDEX idx_locations_coords   ON processed_data.locations (float_latitude, float_longitude);
-- "Is this document important enough for this reader?" - the dashboard's
-- perspective filter, which is an EXISTS on exactly these five columns in
-- exactly this order. Mirrored in init/06-indexes.sql, which unlike this file
-- may be applied to an archive that already exists; 06 also records what the
-- index is measured to be worth on a COMPRESSED archive, which is less than
-- it looks, and why.
CREATE INDEX idx_source_importances_lookup
    ON processed_data.source_importances_by_perspective
       (text_project, text_language, text_task_id, text_fk_source_id, text_perspective);

-- ============================================================
-- monitoring
--
-- Carries the same three columns as everything else. A run covers many tasks,
-- so text_task_id is usually empty here - it is present so a script splitting
-- an archive by project can treat every table in the database identically
-- instead of keeping a list of exceptions.
-- ============================================================

CREATE TABLE monitoring.collector_runs (
    date_added        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name         TEXT NOT NULL,
    text_project      TEXT NOT NULL DEFAULT '',
    text_language     TEXT NOT NULL DEFAULT 'English',
    text_task_id      TEXT NOT NULL DEFAULT '',
    text_key_label    TEXT NOT NULL DEFAULT '',
    text_status       TEXT NOT NULL DEFAULT '',
    integer_jobs_seen INTEGER NOT NULL DEFAULT 0,
    integer_jobs_new  INTEGER NOT NULL DEFAULT 0,
    integer_rows      INTEGER NOT NULL DEFAULT 0,
    text_message      TEXT,
    PRIMARY KEY (date_added, text_name)
);

SELECT create_hypertable('monitoring.collector_runs', 'date_added',
                         chunk_time_interval => INTERVAL '1 day');
ALTER TABLE monitoring.collector_runs SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'text_project',
    timescaledb.compress_orderby = 'date_added DESC'
);
-- Thirty days, like the archive tables above and for the same reason.
-- The policy lives in init/05-policies.sql, which owns every retention and
-- compression number in one place and, unlike this file, may be applied to an
-- archive that already exists.
CREATE INDEX idx_runs_project  ON monitoring.collector_runs (text_project);
CREATE INDEX idx_runs_language ON monitoring.collector_runs (text_language);
CREATE INDEX idx_runs_task     ON monitoring.collector_runs (text_task_id);
CREATE INDEX idx_runs_status   ON monitoring.collector_runs (text_status);
