-- ============================================================
-- Dashboard - its own schema
--
-- Everything the dashboard WRITES lives here. processed_data is the archive
-- and stays read-only from the dashboard's point of view: the collector is the
-- only thing that writes there, and a dashboard that could edit results would
-- turn "what the extraction said" into "what someone last clicked".
--
-- Three kinds of things are kept:
--
--   colour groups   How a connection type is coloured on the map and in the
--                   graph. Connection type names are free text from the
--                   extraction - a real archive holds tens of thousands of
--                   distinct ones - so they are grouped into a dozen categories,
--                   each with one colour. The assignment is a table, not a
--                   regex: the customer changes it on a settings page, and the
--                   same type must never come out in two colours.
--
--   buckets         "Apple Inc.", "Apple" and "Apple (Company)" are one company
--                   to the person looking at the dashboard. A bucket names the
--                   values that should be searched as one. Members are
--                   name + type, not ids: entity ids are shared between the
--                   languages of one task, but not across tasks, so a name is
--                   the only thing that reliably survives. A bucket has a
--                   KIND, so the same mechanism groups entity types, source
--                   types, places, location types, event types, attribute
--                   types, units and market topics as well.
--
--   access tokens   Passwords for the gate that live in the archive rather
--                   than in the environment, so they can be handed out and
--                   revoked without a restart.
--
-- Every statement is idempotent (IF NOT EXISTS / ON CONFLICT DO NOTHING) so
-- the dashboard can run these files on every start and a restart is a no-op.
-- Column names follow the archive's convention: the type is the prefix.
-- ============================================================

-- Not a plain `CREATE SCHEMA IF NOT EXISTS`. PostgreSQL checks the CREATE
-- privilege on the DATABASE before it checks whether the schema is already
-- there, so that statement fails with "permission denied for database" for a
-- role that owns the schema but may not make new ones - which is exactly the
-- least-privilege role init/04-roles.sh creates, and it would stop the
-- dashboard on every start. Asking first costs one catalogue lookup and
-- leaves the grant out of it.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'dashboard') THEN
        EXECUTE 'CREATE SCHEMA dashboard';
    END IF;
END
$$;

-- ── Colour groups ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS dashboard.colour_groups (
    bigint_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_added       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- A stable slug for URLs, JSON and the seed; the name is what is shown.
    text_key         TEXT NOT NULL UNIQUE CHECK (text_key ~ '^[a-z][a-z0-9_-]*$'),
    text_name        TEXT NOT NULL,
    -- Six-digit hex only. A named CSS colour or an rgba() would render, but the
    -- contrast check and the PDF export both need to read the value back.
    text_colour      TEXT NOT NULL CHECK (text_colour ~ '^#[0-9A-Fa-f]{6}$'),
    text_description TEXT NOT NULL DEFAULT '',
    integer_sort     INTEGER NOT NULL DEFAULT 0,
    -- The group a type lands in when nobody has assigned it. Exactly one row
    -- carries this flag (see the index below), so "unassigned" always has a
    -- defined colour rather than an undefined default.
    bool_fallback    BOOLEAN NOT NULL DEFAULT false
);

-- Exactly one fallback: a partial unique index over a constant admits one row
-- where bool_fallback is true and any number where it is false.
CREATE UNIQUE INDEX IF NOT EXISTS idx_colour_groups_one_fallback
    ON dashboard.colour_groups ((true)) WHERE bool_fallback;

-- One row per connection type NAME, across every project and language. The
-- name is the key because that is what processed_data.connections carries;
-- a translated type ("Lieferant") is its own row and gets its own assignment.
CREATE TABLE IF NOT EXISTS dashboard.colour_group_types (
    text_type_name   TEXT PRIMARY KEY,
    bigint_fk_group  BIGINT NOT NULL
                     REFERENCES dashboard.colour_groups (bigint_id) ON DELETE CASCADE,
    -- 'suggested' rows were written by the keyword helper on first seed and
    -- are shown as such, so a person can tell a guess from a decision.
    text_source      TEXT NOT NULL DEFAULT 'manual'
                     CHECK (text_source IN ('manual', 'suggested')),
    date_added       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    date_updated     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_colour_group_types_group
    ON dashboard.colour_group_types (bigint_fk_group);

-- ── Buckets ──────────────────────────────────────────────────

-- A BUCKET HAS A KIND. "Apple Inc." and "Apple" are one company - and
-- "Company", "Unternehmen" and "AG" are one entity TYPE, "Rotterdam" and
-- "Rotterdam Port" one area, "t" and "tonne" one unit. It is the same problem
-- every time: an archive built from free text calls one thing several names,
-- and a person should be able to say "these are the same" once and have every
-- search honour it.
--
--   entity          a member is name + type ("Apple Inc.", Company)
--   entity_type     a member is a type name (Company, Unternehmen, AG)
--   source_type     Press release, Pressemitteilung
--   location        an address or a place from dashboard.places
--   location_type   Headquarters, Hauptsitz, Head office
--   event_type      Product launch, Produkteinführung
--   attribute_type  Revenue, Umsatz, Turnover
--   unit            t, tonne, metric ton
--   market_topic    Semiconductors, Halbleiter
--
-- connection_type is deliberately NOT a kind. dashboard.colour_groups
-- already groups connection types - one colour per group, assigned in a
-- table - and a second grouping for the same thing in a different place is
-- how a product starts contradicting itself. app/scope.py reads a colour
-- group wherever it would read a bucket, so the grouping is usable in a
-- search without existing twice; both settings pages say so.
--
-- A member's text_type keeps its meaning only for kind='entity'. Every other
-- kind groups plain values, and its members carry NULL there.
CREATE TABLE IF NOT EXISTS dashboard.buckets (
    bigint_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_added       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    text_name        TEXT NOT NULL CHECK (btrim(text_name) <> ''),
    -- NULL means the bucket applies to every project. NULLS NOT DISTINCT so
    -- two "every project" buckets of the same name are still a conflict.
    text_project     TEXT,
    text_kind        TEXT NOT NULL DEFAULT 'entity',
    -- The uniqueness includes the kind: an entity bucket called "Company" and
    -- an entity-TYPE bucket of that name are two different things that
    -- happen to share a word.
    CONSTRAINT buckets_name_project_kind_key
        UNIQUE NULLS NOT DISTINCT (text_name, text_project, text_kind),
    CONSTRAINT buckets_kind_is_known
        CHECK (text_kind IN ('entity', 'entity_type', 'source_type', 'location',
                             'location_type', 'event_type', 'attribute_type',
                             'unit', 'market_topic'))
);

-- Every lookup starts "the buckets of this kind that apply to this project".
CREATE INDEX IF NOT EXISTS idx_buckets_kind_project
    ON dashboard.buckets (text_kind, text_project);

CREATE TABLE IF NOT EXISTS dashboard.bucket_members (
    bigint_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_added       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    bigint_fk_bucket BIGINT NOT NULL
                     REFERENCES dashboard.buckets (bigint_id) ON DELETE CASCADE,
    text_name        TEXT NOT NULL CHECK (btrim(text_name) <> ''),
    -- NULL type means "this name, whatever its type". Given, it keeps
    -- Apple (Company) apart from Apple (Fruit).
    text_type        TEXT
);

-- Case-insensitive uniqueness, because that is how members are matched.
CREATE UNIQUE INDEX IF NOT EXISTS idx_bucket_members_unique
    ON dashboard.bucket_members
       (bigint_fk_bucket, lower(text_name), lower(coalesce(text_type, '')));

-- ── Housekeeping ─────────────────────────────────────────────

-- Key/value for the few switches that are not worth a table of their own
-- (the crawler's global pause, for one).
CREATE TABLE IF NOT EXISTS dashboard.settings (
    text_key         TEXT PRIMARY KEY,
    text_value       TEXT NOT NULL DEFAULT '',
    date_updated     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Which revision of these files has been applied. A later change to the
-- schema adds a row here and a migration keyed on it, instead of editing
-- the CREATE statements above.
CREATE TABLE IF NOT EXISTS dashboard.schema_version (
    integer_version  INTEGER PRIMARY KEY,
    date_added       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO dashboard.schema_version (integer_version) VALUES (1)
ON CONFLICT DO NOTHING;

-- ============================================================
-- Tokens that open the gate, kept in the archive
--
-- DASHBOARD_GATE_PASSWORD (dashboard/app/gate.py) is the right place for the
-- one password an installation is set up with, and the wrong place for the
-- fifth. Every change to that variable means editing a file on the server and
-- restarting the container - and because the cookie is signed with the whole
-- set, it also logs everybody else out. Letting a colleague in until March
-- should not cost any of that, and taking the access away again should not
-- wait for the next deployment.
--
-- So the gate reads a second source: a row here is a password with a label,
-- an expiry and a switch. `database/manage_tokens.sh` writes them, and the
-- gate treats a row as live when `bool_enabled` is true and `date_expires`
-- is either NULL or still in the future.
--
-- THE TOKEN IS STORED AS IT WAS HANDED OUT, not as a hash of it, and that is
-- a decision rather than an oversight. It is a shared bearer secret with no
-- account behind it: the person who administers the archive has to be able
-- to read one back and send it again, which is exactly what the list in
-- manage_tokens.sh is for. Nothing is protected by hashing it either -
-- anybody who can read this table can already read every document in the
-- archive it guards, which is the thing the gate exists to keep from
-- strangers.
--
-- ============================================================

CREATE TABLE IF NOT EXISTS dashboard.access_tokens (
    bigint_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- What is typed into the gate form. UNIQUE so the same string cannot be
    -- issued to two people and then revoked for one of them.
    text_token       TEXT UNIQUE NOT NULL,
    -- Who it was given to, or what it is for. For the person administering
    -- the archive and for the log line that says which token was used; it is
    -- never shown to somebody who has not passed the gate, because that
    -- would be a list of who has access.
    text_label       TEXT NOT NULL,
    -- The soft revoke. Turning a token off keeps the row, so the label and
    -- the date it was last used survive the decision - which a DELETE does
    -- not, and which is what somebody asks about a week later.
    bool_enabled     BOOLEAN NOT NULL DEFAULT true,
    -- NULL means it never expires. Every token manage_tokens.sh issues gets
    -- a date, because access that has to be renewed is access somebody has
    -- thought about twice.
    date_expires     TIMESTAMPTZ,
    -- Stamped by the gate when the token opens it, so an unused token can be
    -- told from a working one before it is withdrawn.
    date_last_used   TIMESTAMPTZ,
    date_added       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The gate asks one question, every 30 seconds: which rows are live? That is
-- exactly this index's two columns, in that order.
CREATE INDEX IF NOT EXISTS idx_access_tokens_live
    ON dashboard.access_tokens (bool_enabled, date_expires);
